---
wgeasy_version: "latest"
wgeasy_install_dir: "/opt/docker/wg-easy"

wgeasy_webui_port: 51821

# https://github.com/wg-easy/wg-easy?tab=readme-ov-file#options
wgeasy_env: {}

wgeasy_docker_settings: {}
