---
# https://hub.docker.com/r/filebrowser/filebrowser/tags
filebrowser_version: "latest"
filebrowser_port: 8081
filebrowser_install_dir: "/opt/docker/filebrowser"

filebrowser_storage_root_dir: "/opt"

# https://filebrowser.org/configuration
filebrowser_env: {}

filebrowser_docker_settings: {}
