---
- name: "Make sure {{ changedetection_docker_settings.network }} docker network exists"
  community.general.docker_network:
    name: "{{ changedetection_docker_settings.network }}"
    state: "present"

- name: "Install and configure Selenium"
  ansible.builtin.include_tasks: "selenium.yml"

- name: "Install and configure changedetection.io"
  ansible.builtin.include_tasks: "changedetection.yml"
