name: "Setup"
description: "Installs dependencies and sets up the environment"

runs:
  using: "composite"

  steps:
    - name: "Print Ansible environment"
      run: "ansible --version"
      shell: "bash"

    - name: "Install from requirements.yml"
      run: |
        # Make passlib available in python environment
        # https://docs.ansible.com/ansible/latest/reference_appendices/faq.html#how-do-i-generate-encrypted-passwords-for-the-user-module
        /opt/pipx/venvs/ansible-core/bin/python -m pip install passlib

        ansible-galaxy install -r .github/playbook/requirements.yml
      shell: "bash"
