---
- name: "Prepare task variables"
  ansible.builtin.set_fact:
    cloudflare_service_id: "cloudflare"
    cloudflare_root_dir: "/opt/docker/cloudflare"

- name: "Prepare task variables"
  ansible.builtin.set_fact:
    tunnel_networks: "{{ tunnel_networks | default([]) + [{'name': item}] }}"
  with_items: "{{ cloudflare_tunnel_networks }}"

- name: "Run cloudflared container"
  community.general.docker_container:
    name: "{{ cloudflare_service_id }}"
    image: "cloudflare/cloudflared:{{ cloudflare_tunnel_version }}"
    networks: "{{ tunnel_networks | default([]) | list }}"
    state: "started"
    env:
      TUNNEL_TOKEN: "{{ cloudflare_tunnel_token }}"
    command: "tunnel --no-autoupdate run"
    restart_policy: "unless-stopped"
