---
- name: "Run roles"
  hosts: "localhost"
  become: true
  roles:
    - { role: "artyorsh.selfhosted.docker", tags: "docker" }
    - { role: "artyorsh.selfhosted.authelia", tags: "authelia" }
    - { role: "artyorsh.selfhosted.duplicati", tags: "duplicati" }
    - { role: "artyorsh.selfhosted.glances", tags: "glances" }
    - { role: "artyorsh.selfhosted.forgejo", tags: "forgejo" }
    - { role: "artyorsh.selfhosted.homebox", tags: "homebox" }
    # FIXME: miniflux is deployed together with rssbridge. Not possible to test separately, but miniflux is higher priority.
    - { role: "artyorsh.selfhosted.rss", tags: "miniflux" }
    - { role: "artyorsh.selfhosted.nginx-proxy-manager", tags: "nginx-proxy-manager" }
    - { role: "artyorsh.selfhosted.paperlessngx", tags: "paperlessngx" }
    - { role: "artyorsh.selfhosted.vaultwarden", tags: "vaultwarden" }
    - { role: "artyorsh.selfhosted.wallos", tags: "wallos" }
    - { role: "artyorsh.selfhosted.wgeasy", tags: "wgeasy" }
